In [4]:
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits import mplot3d
import pandas as pd


In [6]:
import re
def parse_css_to_array(css_file):
    with open(css_file, "r") as f:
        lines = f.readlines()
    
    shape_line = lines[0]
    shape = tuple(map(int, re.findall(r'\d+', shape_line)))
    
    data = []

    for line in lines[1:]:
        if "--data" in line:
            values = line.split(':')[1].replace(';', '').strip().split(', ')
            values = [float(v) for v in values]
            data.append(values)

    
   
    # Reshape the data into the original array shape
    tracks = np.array(data).reshape(shape)
    return tracks

In [7]:
tracks = parse_css_to_array('data.css')

In [9]:
print(len(tracks))
print(len(tracks[0]))
print(tracks)


16
1000000
[[[48.43539429 17.10258484 84.12322235]
  [48.43539429 17.10258484 84.12322235]
  [48.43539429 17.10258484 84.12322235]
  ...
  [48.43539429 17.10258484 84.12322235]
  [48.43539429 17.10258484 84.12322235]
  [48.43539429 17.10258484 84.12322235]]

 [[48.43539429 17.10258484 84.12322235]
  [44.96483231 23.98258209 77.67933655]
  [51.44758224 20.46845627 74.32398224]
  ...
  [48.43539429 17.10258484 84.12322235]
  [48.43539429 17.10258484 84.12322235]
  [48.43539429 17.10258484 84.12322235]]

 [[48.43539429 17.10258484 84.12322235]
  [44.96483231 23.98258209 77.67933655]
  [51.44758224 20.46845627 74.32398224]
  ...
  [48.43539429 17.10258484 84.12322235]
  [48.43539429 17.10258484 84.12322235]
  [48.43539429 17.10258484 84.12322235]]

 ...

 [[48.43539429 17.10258484 84.12322235]
  [44.96483231 23.98258209 77.67933655]
  [51.44758224 20.46845627 74.32398224]
  ...
  [48.43539429 17.10258484 84.12322235]
  [48.43539429 17.10258484 84.12322235]
  [48.43539429 17.10258484 84.123

In [ ]:
figure = plt.figure() 
axes = mplot3d.Axes3D(figure)
num_tracks_to_plot = min(1000, len(tracks))  # Ensure not to exceed available tracks
plotted_indices = np.random.choice(len(tracks), num_tracks_to_plot, replace=False)

for i in plotted_indices:
    track = tracks[i]
    idx = track_indices[i]
    did_detect = self.tallies["SURFACE_DETECT"][idx]
    did_reflect_specular = self.particle_histories["REFLECT_SPECULAR"][idx].astype(bool)
    did_reflect_diffuse = self.particle_histories["REFLECT_DIFFUSE"][idx].astype(bool)
    did_scatter = self.particle_histories["RAYLEIGH_SCATTER"][idx] != 0

    if did_reflect_diffuse and did_reflect_diffuse:
        color = "purple"
    elif did_reflect_diffuse:
        color = "red"
    elif did_reflect_specular:
        color = "blue"
    elif did_scatter:
        color = "black"
    else:
        color = "green"

    axes.plot(
        track[:, 0], track[:, 1], track[:, 2], color=color, linewidth=linewidth
            )

    if plot_geometry:
        geometry_df = pd.read_csv(self.geometry_data_path)
        stl_names = geometry_df["stl_filepath"]
        colors = geometry_df["color"]
        y_displacement = geometry_df["displacement y"]
        z_displacement = geometry_df["displacement z"]

        for (
            curr_filename,
            curr_color,
            current_y_displacement,
            current_z_displacement,
            ) in zip(stl_names, colors, y_displacement, z_displacement):
                if curr_filename not in self.gm.exclude:
                    your_mesh = mesh.Mesh.from_file(curr_filename)
                    mesh_dimension = np.shape(your_mesh.vectors)
                    for i in range(mesh_dimension[1]):
                        your_mesh.vectors[:, i, 1] += current_y_displacement
                    for k in range(mesh_dimension[1]):
                        your_mesh.vectors[:, i, 2] += current_z_displacement
                    poly3d = mplot3d.art3d.Poly3DCollection(your_mesh.vectors)
                    poly3d.set_alpha(0.2)
                    poly3d.set_edgecolor(None)
                    poly3d.set_facecolor(curr_color)
                    axes.add_collection3d(poly3d)
            # Auto scale to the mesh size
        scale = your_mesh.points.flatten()

        axes.auto_scale_xyz(scale, scale, scale)
        axes.set_xlabel("x position (mm)")
        axes.set_ylabel("y position (mm)")
        axes.set_zlabel("z position (mm)")
        figure.suptitle(title)
        plt.title(title)
        self.save_plot(plt, title.replace(" ", "_").lower())